zendservershopware:
  build: ./zend85
  ports:
    - 8080:80
    - 10081:10081
    - 10137:10137
  environment:
    - ZEND_ADMIN_PASSWORD=admin
  links:
    - mariadb

mariadb:
  image: mariadb
  ports:
      - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=dev
    - MYSQL_USER=dev
    - MYSQL_PASSWORD=dev
    - MYSQL_DATABASE=shopware
